Repository UQcsse3200/2025-studio-2, pull requests merged in 2025-09, with the labels that each got.

#43 More Puzzle Functionality - Traps, Boxes (Lifting and Autonomous), Button Interactions
  source/core/assets/images/box_blue.png
  source/core/assets/images/box_orange.png
  source/core/assets/images/box_red.png
  source/core/assets/images/box_white.png
  source/core/assets/images/img.png
  source/core/assets/images/spikes_sprite.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/AutonomousBoxComponent.java
  source/core/src/main/com/csse3200/game/components/ButtonComponent.java
  source/core/src/main/com/csse3200/game/components/MoveableBoxComponent.java
  source/core/src/main/com/csse3200/game/components/obstacles/TrapComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/entities/factories/BoxFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TrapFactory.java
  source/core/src/main/com/csse3200/game/physics/ObjectContactListener.java
  source/core/src/test/com/csse3200/game/components/AutonomousBoxComponentTest.java
  source/core/src/test/com/csse3200/game/components/ButtonComponentTest.java
  source/core/src/test/com/csse3200/game/components/MoveableBoxComponentTest.java
  source/core/src/test/com/csse3200/game/components/TrapComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/BoxFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ButtonFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/TrapFactoryTest.java
Labels: team 3, sprint 1

#51 Puzzle Base Functionality: Collision support for collectables and doors
  source/core/assets/images/blue_button.png
  source/core/assets/images/blue_button_pushed.png
  source/core/assets/images/button.png
  source/core/assets/images/button_pushed.png
  source/core/assets/images/door_closed.png
  source/core/assets/images/door_open.png
  source/core/assets/images/key.png
  source/core/assets/images/key_tester.png
  source/core/assets/images/red_button.png
  source/core/assets/images/red_button_pushed.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/collectables/CollectableComponent.java
  source/core/src/main/com/csse3200/game/components/lighting/ConeLightComponent.java
  source/core/src/main/com/csse3200/game/components/obstacles/DoorComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/CollectableFactory.java
  source/core/src/main/com/csse3200/game/physics/ObjectContactListener.java
  source/core/src/test/com/csse3200/game/components/lighting/ConeLightComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/DoorComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/KeyComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/CollectableFactoryTest.java
Labels: team 3, sprint 1

#58 UI
  source/core/assets/inventory-screen/inventory-selected.png
  source/core/assets/inventory-screen/inventory_selected.png
  source/core/assets/inventory-screen/map-selected.png
  source/core/assets/inventory-screen/map_selected.png
  source/core/assets/inventory-screen/no_buttons.png
  source/core/assets/inventory-screen/upgrade_selected.png
  source/core/assets/inventory-screen/upgrades-selected.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/CaveGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/components/minimap/MinimapComponent.java
  source/core/src/main/com/csse3200/game/components/minimap/MinimapDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/MapDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/player/InventoryEntityLocator.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/tooltip/TooltipSystem.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/files/UserSettings.java
  source/core/src/main/com/csse3200/game/input/Keymap.java
  source/core/src/main/com/csse3200/game/input/PauseInputComponent.java
  source/core/src/main/com/csse3200/game/input/SettingsInputComponent.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/services/MinimapService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/Inventory.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/InventoryTab.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/InventoryTabInterface.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/MapTab.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/SettingsTab.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/UpgradesTab.java
  source/core/src/test/com/csse3200/game/components/settingsmenu/SettingsMenuDisplayTest.java
  source/core/src/test/com/csse3200/game/components/tooltip/TooltipSystemTest.java
  source/core/src/test/com/csse3200/game/files/UserSettingsTest.java
  source/core/src/test/com/csse3200/game/input/KeymapTest.java
  source/core/src/test/com/csse3200/game/input/PauseInputComponentTest.java
  source/core/src/test/com/csse3200/game/input/SettingsInputComponentTest.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTabTest.java
  source/core/src/test/com/csse3200/game/ui/inventoryscreen/SettingsTabTest.java
  source/core/src/test/com/csse3200/game/ui/terminal/InitializerTest.java
Labels: feature, team 2, sprint 1

#110 Enemy Activation & New Chase Conditions
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/SprintOneGameArea.java
  source/core/src/main/com/csse3200/game/components/enemy/ActivationComponent.java
  source/core/src/main/com/csse3200/game/components/npc/ExplosionAnimationController.java
  source/core/src/main/com/csse3200/game/components/projectiles/BombComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/BombChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/CooldownTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PatrolTask.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ExplosionFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/test/com/csse3200/game/components/enemy/ActivationComponentTest.java
  source/core/src/test/com/csse3200/game/components/enemy/PatrolRouteComponentTest.java
  source/core/src/test/com/csse3200/game/components/enemy/SpawnPositionComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/DroneAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/tasks/BombChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/CooldownTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PatrolTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ExplosionFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ProjectileFactoryTest.java
Labels: team 5, sprint 2

#120 Level two addition
  source/core/assets/images/Door_Gate of the Demon.png
  source/core/assets/images/Platform_Black and Blue.png
  source/core/assets/images/Platform_stove.png
  source/core/assets/images/Wall_Black and Blue.png
  source/core/assets/images/Wall_Demon Spirit Statue.png
  source/core/assets/images/Wall_Golden Gate.png
  source/core/assets/images/Wall_Statue on the left.png
  source/core/assets/images/Wall_Statue on the right.png
  source/core/src/main/com/csse3200/game/areas/CaveGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/LevelOneGameArea.java
  source/core/src/main/com/csse3200/game/areas/LevelTwoGameArea.java
  source/core/src/main/com/csse3200/game/areas/SprintOneGameArea.java
  source/core/src/main/com/csse3200/game/areas/TemplateGameArea.java
  source/core/src/main/com/csse3200/game/components/CameraComponent.java
  source/core/src/main/com/csse3200/game/components/DeathZoneComponent.java
  source/core/src/main/com/csse3200/game/components/obstacles/DoorComponent.java
  source/core/src/main/com/csse3200/game/components/platforms/ButtonTriggeredPlatformComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/DeathZoneFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/ui/cutscene/CutsceneDisplay.java
  source/core/src/test/com/csse3200/game/components/DeathZoneComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/DoorComponentTest.java
  source/core/src/test/com/csse3200/game/ui/cutscene/CutsceneDisplayTest.java
Labels: feature, team 4, sprint 2

#119 UI Enchancements & Asset Reworks - Some updated assets and UI changes
  source/core/assets/images/cavelevel/background/1.png
  source/core/assets/images/cavelevel/background/2.png
  source/core/assets/images/cavelevel/background/3.png
  source/core/assets/images/cavelevel/background/4.png
  source/core/assets/images/cavelevel/background/5.png
  source/core/assets/images/cavelevel/background/6.png
  source/core/assets/images/cavelevel/background/7.png
  source/core/assets/images/cavelevel/cave_floor.atlas
  source/core/assets/images/cavelevel/cave_floor.png
  source/core/assets/images/cavelevel/cavebackground.png
  source/core/assets/images/cavelevel/cavebackgroundtile.png
  source/core/assets/images/cavelevel/platformcentretile.png
  source/core/assets/images/cavelevel/platformendtile.png
  source/core/assets/images/cavelevel/tile000.png
  source/core/assets/images/cavelevel/tile001.png
  source/core/assets/images/cavelevel/tile002.png
  source/core/assets/images/cavelevel/tile014.png
  source/core/assets/images/cavelevel/tile015.png
  source/core/assets/images/cavelevel/tile016.png
  source/core/assets/images/cavelevel/tile028.png
  source/core/assets/images/cavelevel/tile029.png
  source/core/assets/images/cavelevel/tile030.png
  source/core/assets/images/key.png
  source/core/assets/images/platform.png
  source/core/src/main/com/csse3200/game/areas/LevelOneGameArea.java
  source/core/src/main/com/csse3200/game/areas/TemplateGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryNavigationComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/minimap/MinimapDisplay.java
  source/core/src/main/com/csse3200/game/components/pausemenu/PauseMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/tooltip/TooltipSystem.java
  source/core/src/main/com/csse3200/game/entities/factories/FloorFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TrapFactory.java
  source/core/src/main/com/csse3200/game/input/PauseInputComponent.java
  source/core/src/main/com/csse3200/game/rendering/ParallaxBackgroundComponent.java
  source/core/src/main/com/csse3200/game/rendering/ParallaxLayer.java
  source/core/src/main/com/csse3200/game/rendering/TiledFloorComponent.java
  source/core/src/main/com/csse3200/game/rendering/TiledGroundFloorComponent.java
  source/core/src/main/com/csse3200/game/rendering/TiledPlatformComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/ui/PixelPerfectPlacer.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/InventoryTab.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/ObjectivesTab.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/SettingsTab.java
  source/core/src/main/com/csse3200/game/ui/inventoryscreen/UpgradesTab.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTabTest.java
  source/core/src/test/com/csse3200/game/ui/PixelPerfectPlacerTest.java
Labels: team 2, sprint 2

#139 Team 3 puzzles
  source/core/assets/configs/items.json
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/BoxPressurePlateComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/CollectablesConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/CollectableFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PressurePlateFactory.java
  source/core/src/test/com/csse3200/game/components/BoxPressurePlateComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PressurePlateFactoryTest.java
Labels: team 3, sprint 2
